<?php

use Illuminate\Database\Seeder;

class ExercisesTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('exercises')->insert(['id' => 44,'label' => '180 Jump Squats','exercisetype_id' => 2,'difficulty_id' => 3,'isHomeSafe' => false,'isreps' => true]);
        DB::table('exercises')->insert(['id' => 79,'label' => '4-Count Burpees','exercisetype_id' => 3,'difficulty_id' => 1,'isHomeSafe' => false,'isreps' => true]);
        DB::table('exercises')->insert(['id' => 86,'label' => '6-Count Burpees','exercisetype_id' => 3,'difficulty_id' => 3,'isHomeSafe' => false,'isreps' => true]);
        DB::table('exercises')->insert(['id' => 18,'label' => 'Alligator Push-ups','exercisetype_id' => 1,'difficulty_id' => 3,'isHomeSafe' => true,'isreps' => true]);
        DB::table('exercises')->insert(['id' => 200,'label' => 'Arm Circles Backward','exercisetype_id' => 1,'difficulty_id' => 1,'isHomeSafe' => true,'isreps' => true]);
        DB::table('exercises')->insert(['id' => 199,'label' => 'Arm Circles Forward','exercisetype_id' => 1,'difficulty_id' => 1,'isHomeSafe' => true,'isreps' => true]);
        DB::table('exercises')->insert(['id' => 91,'label' => 'Backward Lunges','exercisetype_id' => 2,'difficulty_id' => 1,'isHomeSafe' => true,'isreps' => true]);
        DB::table('exercises')->insert(['id' => 130,'label' => 'Bicycle Crunches','exercisetype_id' => 5,'difficulty_id' => 2,'isHomeSafe' => true,'isreps' => true]);
        DB::table('exercises')->insert(['id' => 153,'label' => 'Bridge','exercisetype_id' => 5,'difficulty_id' => 1,'isHomeSafe' => true,'isreps' => true]);
        DB::table('exercises')->insert(['id' => 42,'label' => 'Butt Kicker Jump Squats','exercisetype_id' => 2,'difficulty_id' => 3,'isHomeSafe' => false,'isreps' => true]);
        DB::table('exercises')->insert(['id' => 155,'label' => 'Calf Raises','exercisetype_id' => 2,'difficulty_id' => 1,'isHomeSafe' => true,'isreps' => true]);
        DB::table('exercises')->insert(['id' => 190,'label' => 'Child\'s Pose','exercisetype_id' => 6,'difficulty_id' => 1,'isHomeSafe' => true,'isreps' => false]);
        DB::table('exercises')->insert(['id' => 117,'label' => 'Clap Jacks','exercisetype_id' => 4,'difficulty_id' => 1,'isHomeSafe' => false,'isreps' => true]);
        DB::table('exercises')->insert(['id' => 189,'label' => 'Cobblers Stretch','exercisetype_id' => 5,'difficulty_id' => 1,'isHomeSafe' => true,'isreps' => false]);
        DB::table('exercises')->insert(['id' => 9,'label' => 'Commander Push-ups','exercisetype_id' => 1,'difficulty_id' => 2,'isHomeSafe' => true,'isreps' => true]);
        DB::table('exercises')->insert(['id' => 113,'label' => 'Crossing Punches','exercisetype_id' => 4,'difficulty_id' => 1,'isHomeSafe' => true,'isreps' => true]);
        DB::table('exercises')->insert(['id' => 127,'label' => 'Crunches','exercisetype_id' => 5,'difficulty_id' => 1,'isHomeSafe' => true,'isreps' => true]);
        DB::table('exercises')->insert(['id' => 95,'label' => 'Curtsy Lunges','exercisetype_id' => 2,'difficulty_id' => 2,'isHomeSafe' => true,'isreps' => true]);
        DB::table('exercises')->insert(['id' => 187,'label' => 'Declined Wall Push-ups','exercisetype_id' => 1,'difficulty_id' => 3,'isHomeSafe' => true,'isreps' => true]);
        DB::table('exercises')->insert(['id' => 88,'label' => 'Flat Out Burpees Tuck Jumps','exercisetype_id' => 3,'difficulty_id' => 3,'isHomeSafe' => false,'isreps' => true]);
        DB::table('exercises')->insert(['id' => 81,'label' => 'Flat Out Burpees','exercisetype_id' => 3,'difficulty_id' => 2,'isHomeSafe' => false,'isreps' => true]);
        DB::table('exercises')->insert(['id' => 40,'label' => 'Forward Jump Squats','exercisetype_id' => 2,'difficulty_id' => 2,'isHomeSafe' => false,'isreps' => true]);
        DB::table('exercises')->insert(['id' => 89,'label' => 'Forward Lunges','exercisetype_id' => 2,'difficulty_id' => 1,'isHomeSafe' => true,'isreps' => true]);
        DB::table('exercises')->insert(['id' => 106,'label' => 'High Knees','exercisetype_id' => 4,'difficulty_id' => 1,'isHomeSafe' => false,'isreps' => true]);
        DB::table('exercises')->insert(['id' => 46,'label' => 'High Plank','exercisetype_id' => 5,'difficulty_id' => 1,'isHomeSafe' => true,'isreps' => false]);
        DB::table('exercises')->insert(['id' => 58,'label' => 'High Plank Double Knee','exercisetype_id' => 5,'difficulty_id' => 3,'isHomeSafe' => true,'isreps' => true]);
        DB::table('exercises')->insert(['id' => 54,'label' => 'High Plank Jacks','exercisetype_id' => 5,'difficulty_id' => 2,'isHomeSafe' => false,'isreps' => true]);
        DB::table('exercises')->insert(['id' => 59,'label' => 'High Plank Jumping Jacks','exercisetype_id' => 5,'difficulty_id' => 3,'isHomeSafe' => false,'isreps' => true]);
        DB::table('exercises')->insert(['id' => 55,'label' => 'High Plank Jumps','exercisetype_id' => 5,'difficulty_id' => 2,'isHomeSafe' => false,'isreps' => true]);
        DB::table('exercises')->insert(['id' => 52,'label' => 'High Plank Knee Crosses','exercisetype_id' => 5,'difficulty_id' => 2,'isHomeSafe' => true,'isreps' => true]);
        DB::table('exercises')->insert(['id' => 51,'label' => 'High Plank Knee-to-Elbow','exercisetype_id' => 5,'difficulty_id' => 2,'isHomeSafe' => true,'isreps' => true]);
        DB::table('exercises')->insert(['id' => 47,'label' => 'High Plank Leg Lifts','exercisetype_id' => 5,'difficulty_id' => 1,'isHomeSafe' => true,'isreps' => true]);
        DB::table('exercises')->insert(['id' => 60,'label' => 'High Plank Limb Raises','exercisetype_id' => 5,'difficulty_id' => 3,'isHomeSafe' => true,'isreps' => true]);
        DB::table('exercises')->insert(['id' => 49,'label' => 'High Side Plank','exercisetype_id' => 5,'difficulty_id' => 2,'isHomeSafe' => true,'isreps' => false]);
        DB::table('exercises')->insert(['id' => 177,'label' => 'Hip Abduction','exercisetype_id' => 2,'difficulty_id' => 1,'isHomeSafe' => true,'isreps' => true]);
        DB::table('exercises')->insert(['id' => 178,'label' => 'Hip Adduction','exercisetype_id' => 2,'difficulty_id' => 1,'isHomeSafe' => true,'isreps' => true]);
        DB::table('exercises')->insert(['id' => 198,'label' => 'Hip Openers','exercisetype_id' => 2,'difficulty_id' => 1,'isHomeSafe' => true,'isreps' => true]);
        DB::table('exercises')->insert(['id' => 150,'label' => 'Inchworm Tuck Jumps','exercisetype_id' => 4,'difficulty_id' => 3,'isHomeSafe' => false,'isreps' => true]);
        DB::table('exercises')->insert(['id' => 129,'label' => 'Inchworms','exercisetype_id' => 5,'difficulty_id' => 1,'isHomeSafe' => true,'isreps' => true]);
        DB::table('exercises')->insert(['id' => 170,'label' => 'Inclined Wall Push-ups','exercisetype_id' => 1,'difficulty_id' => 1,'isHomeSafe' => true,'isreps' => true]);
        DB::table('exercises')->insert(['id' => 156,'label' => 'Inward Calf Raises','exercisetype_id' => 2,'difficulty_id' => 1,'isHomeSafe' => true,'isreps' => true]);
        DB::table('exercises')->insert(['id' => 111,'label' => 'Jog in Place','exercisetype_id' => 4,'difficulty_id' => 1,'isHomeSafe' => true,'isreps' => false]);
        DB::table('exercises')->insert(['id' => 104,'label' => 'Jump Lunges','exercisetype_id' => 2,'difficulty_id' => 3,'isHomeSafe' => false,'isreps' => true]);
        DB::table('exercises')->insert(['id' => 32,'label' => 'Jump Squats','exercisetype_id' => 2,'difficulty_id' => 2,'isHomeSafe' => false,'isreps' => true]);
        DB::table('exercises')->insert(['id' => 105,'label' => 'Jumping Jacks','exercisetype_id' => 4,'difficulty_id' => 1,'isHomeSafe' => false,'isreps' => true]);
        DB::table('exercises')->insert(['id' => 1,'label' => 'Knee Push-ups','exercisetype_id' => 1,'difficulty_id' => 1,'isHomeSafe' => true,'isreps' => true]);
        DB::table('exercises')->insert(['id' => 133,'label' => 'Knee Tuck Crunches','exercisetype_id' => 5,'difficulty_id' => 2,'isHomeSafe' => true,'isreps' => true]);
        DB::table('exercises')->insert(['id' => 164,'label' => 'Knee Up Downs','exercisetype_id' => 1,'difficulty_id' => 1,'isHomeSafe' => true,'isreps' => true]);
        DB::table('exercises')->insert(['id' => 160,'label' => 'Kneel & Stand','exercisetype_id' => 2,'difficulty_id' => 2,'isHomeSafe' => true,'isreps' => true]);
        DB::table('exercises')->insert(['id' => 191,'label' => 'Kneeling Hip Flexor Stretch','exercisetype_id' => 6,'difficulty_id' => 1,'isHomeSafe' => true,'isreps' => false]);
        DB::table('exercises')->insert(['id' => 120,'label' => 'Lateral Jump Touchdown','exercisetype_id' => 4,'difficulty_id' => 3,'isHomeSafe' => false,'isreps' => true]);
        DB::table('exercises')->insert(['id' => 118,'label' => 'Lateral Jumps','exercisetype_id' => 4,'difficulty_id' => 2,'isHomeSafe' => false,'isreps' => true]);
        DB::table('exercises')->insert(['id' => 135,'label' => 'Leg Raises','exercisetype_id' => 5,'difficulty_id' => 2,'isHomeSafe' => true,'isreps' => true]);
        DB::table('exercises')->insert(['id' => 23,'label' => 'Limb Raise Push-ups','exercisetype_id' => 1,'difficulty_id' => 3,'isHomeSafe' => true,'isreps' => true]);
        DB::table('exercises')->insert(['id' => 61,'label' => 'Low Plank','exercisetype_id' => 5,'difficulty_id' => 1,'isHomeSafe' => true,'isreps' => false]);
        DB::table('exercises')->insert(['id' => 66,'label' => 'Low Plank Arm Reaches','exercisetype_id' => 5,'difficulty_id' => 2,'isHomeSafe' => true,'isreps' => true]);
        DB::table('exercises')->insert(['id' => 75,'label' => 'Low Plank Double Knee','exercisetype_id' => 5,'difficulty_id' => 3,'isHomeSafe' => true,'isreps' => true]);
        DB::table('exercises')->insert(['id' => 68,'label' => 'Low Plank Knee Crosses','exercisetype_id' => 5,'difficulty_id' => 2,'isHomeSafe' => true,'isreps' => true]);
        DB::table('exercises')->insert(['id' => 67,'label' => 'Low Plank Knee-to-Elbow','exercisetype_id' => 5,'difficulty_id' => 2,'isHomeSafe' => true,'isreps' => true]);
        DB::table('exercises')->insert(['id' => 69,'label' => 'Low Plank Twists','exercisetype_id' => 5,'difficulty_id' => 2,'isHomeSafe' => true,'isreps' => true]);
        DB::table('exercises')->insert(['id' => 63,'label' => 'Low Side Plank','exercisetype_id' => 5,'difficulty_id' => 1,'isHomeSafe' => true,'isreps' => false]);
        DB::table('exercises')->insert(['id' => 74,'label' => 'Low Side Plank Twists','exercisetype_id' => 5,'difficulty_id' => 3,'isHomeSafe' => true,'isreps' => true]);
        DB::table('exercises')->insert(['id' => 98,'label' => 'Lunge & Twist','exercisetype_id' => 2,'difficulty_id' => 2,'isHomeSafe' => true,'isreps' => true]);
        DB::table('exercises')->insert(['id' => 103,'label' => 'Lunge High Knee Jumps','exercisetype_id' => 2,'difficulty_id' => 3,'isHomeSafe' => false,'isreps' => true]);
        DB::table('exercises')->insert(['id' => 93,'label' => 'Lunge to Front Kick','exercisetype_id' => 2,'difficulty_id' => 2,'isHomeSafe' => true,'isreps' => true]);
        DB::table('exercises')->insert(['id' => 92,'label' => 'Lunge to High Knee','exercisetype_id' => 2,'difficulty_id' => 2,'isHomeSafe' => true,'isreps' => true]);
        DB::table('exercises')->insert(['id' => 193,'label' => 'Lying Figure 4 Stretch','exercisetype_id' => 6,'difficulty_id' => 1,'isHomeSafe' => true,'isreps' => false]);
        DB::table('exercises')->insert(['id' => 180,'label' => 'Marching Wall Sit','exercisetype_id' => 2,'difficulty_id' => 2,'isHomeSafe' => true,'isreps' => true]);
        DB::table('exercises')->insert(['id' => 48,'label' => 'Mod. High Side Plank','exercisetype_id' => 5,'difficulty_id' => 1,'isHomeSafe' => true,'isreps' => false]);
        DB::table('exercises')->insert(['id' => 64,'label' => 'Mod. Low Side Plank','exercisetype_id' => 5,'difficulty_id' => 1,'isHomeSafe' => true,'isreps' => false]);
        DB::table('exercises')->insert(['id' => 124,'label' => 'Mountain Climbers','exercisetype_id' => 4,'difficulty_id' => 1,'isHomeSafe' => true,'isreps' => true]);
        DB::table('exercises')->insert(['id' => 87,'label' => 'Narrow 6 Count Burpees','exercisetype_id' => 3,'difficulty_id' => 3,'isHomeSafe' => false,'isreps' => true]);
        DB::table('exercises')->insert(['id' => 2,'label' => 'Narrow Knee Push-ups','exercisetype_id' => 1,'difficulty_id' => 1,'isHomeSafe' => true,'isreps' => true]);
        DB::table('exercises')->insert(['id' => 5,'label' => 'Narrow Push-ups','exercisetype_id' => 1,'difficulty_id' => 1,'isHomeSafe' => true,'isreps' => true]);
        DB::table('exercises')->insert(['id' => 28,'label' => 'Narrow Squats','exercisetype_id' => 2,'difficulty_id' => 1,'isHomeSafe' => true,'isreps' => true]);
        DB::table('exercises')->insert(['id' => 19,'label' => 'Narrow-to-Wide Push-ups','exercisetype_id' => 1,'difficulty_id' => 3,'isHomeSafe' => false,'isreps' => true]);
        DB::table('exercises')->insert(['id' => 82,'label' => 'One Legged 4 Count Burpees','exercisetype_id' => 3,'difficulty_id' => 2,'isHomeSafe' => false,'isreps' => true]);
        DB::table('exercises')->insert(['id' => 84,'label' => 'One Legged 6 Count Burpees','exercisetype_id' => 3,'difficulty_id' => 3,'isHomeSafe' => false,'isreps' => true]);
        DB::table('exercises')->insert(['id' => 157,'label' => 'Outward Calf Raises','exercisetype_id' => 2,'difficulty_id' => 1,'isHomeSafe' => true,'isreps' => true]);
        DB::table('exercises')->insert(['id' => 35,'label' => 'Overhead Squats','exercisetype_id' => 2,'difficulty_id' => 2,'isHomeSafe' => true,'isreps' => true]);
        DB::table('exercises')->insert(['id' => 195,'label' => 'Overhead Triceps Stretch','exercisetype_id' => 6,'difficulty_id' => 1,'isHomeSafe' => true,'isreps' => false]);
        DB::table('exercises')->insert(['id' => 94,'label' => 'Pendulum Lunges','exercisetype_id' => 2,'difficulty_id' => 2,'isHomeSafe' => true,'isreps' => true]);
        DB::table('exercises')->insert(['id' => 166,'label' => 'Pike Push-ups','exercisetype_id' => 1,'difficulty_id' => 2,'isHomeSafe' => true,'isreps' => true]);
        DB::table('exercises')->insert(['id' => 45,'label' => 'Pistol Squats','exercisetype_id' => 2,'difficulty_id' => 3,'isHomeSafe' => true,'isreps' => true]);
        DB::table('exercises')->insert(['id' => 97,'label' => 'Pivot Lunges','exercisetype_id' => 2,'difficulty_id' => 2,'isHomeSafe' => true,'isreps' => true]);
        DB::table('exercises')->insert(['id' => 34,'label' => 'Plié Jump Squats','exercisetype_id' => 2,'difficulty_id' => 2,'isHomeSafe' => false,'isreps' => true]);
        DB::table('exercises')->insert(['id' => 29,'label' => 'Plié Squats','exercisetype_id' => 2,'difficulty_id' => 1,'isHomeSafe' => true,'isreps' => true]);
        DB::table('exercises')->insert(['id' => 20,'label' => 'Plyo Push-ups','exercisetype_id' => 1,'difficulty_id' => 3,'isHomeSafe' => false,'isreps' => true]);
        DB::table('exercises')->insert(['id' => 36,'label' => 'Prisoner Squats','exercisetype_id' => 2,'difficulty_id' => 2,'isHomeSafe' => true,'isreps' => true]);
        DB::table('exercises')->insert(['id' => 30,'label' => 'Pulsing Squats','exercisetype_id' => 2,'difficulty_id' => 1,'isHomeSafe' => true,'isreps' => true]);
        DB::table('exercises')->insert(['id' => 112,'label' => 'Punches','exercisetype_id' => 4,'difficulty_id' => 1,'isHomeSafe' => true,'isreps' => true]);
        DB::table('exercises')->insert(['id' => 22,'label' => 'Push-up Jacks','exercisetype_id' => 1,'difficulty_id' => 3,'isHomeSafe' => false,'isreps' => true]);
        DB::table('exercises')->insert(['id' => 11,'label' => 'Push-up Shoulder Taps','exercisetype_id' => 1,'difficulty_id' => 2,'isHomeSafe' => true,'isreps' => true]);
        DB::table('exercises')->insert(['id' => 10,'label' => 'Push-up Side Planks','exercisetype_id' => 1,'difficulty_id' => 2,'isHomeSafe' => true,'isreps' => true]);
        DB::table('exercises')->insert(['id' => 4,'label' => 'Push-ups','exercisetype_id' => 1,'difficulty_id' => 1,'isHomeSafe' => true,'isreps' => true]);
        DB::table('exercises')->insert(['id' => 131,'label' => 'Quadruped Limb Raises','exercisetype_id' => 5,'difficulty_id' => 1,'isHomeSafe' => true,'isreps' => true]);
        DB::table('exercises')->insert(['id' => 115,'label' => 'Quick Feet','exercisetype_id' => 4,'difficulty_id' => 1,'isHomeSafe' => false,'isreps' => false]);
        DB::table('exercises')->insert(['id' => 134,'label' => 'Reverse Crunches','exercisetype_id' => 5,'difficulty_id' => 2,'isHomeSafe' => true,'isreps' => true]);
        DB::table('exercises')->insert(['id' => 142,'label' => 'Reverse Plank','exercisetype_id' => 5,'difficulty_id' => 2,'isHomeSafe' => true,'isreps' => false]);
        DB::table('exercises')->insert(['id' => 109,'label' => 'Rockstars','exercisetype_id' => 4,'difficulty_id' => 1,'isHomeSafe' => false,'isreps' => true]);
        DB::table('exercises')->insert(['id' => 139,'label' => 'Russian Twist Easy','exercisetype_id' => 5,'difficulty_id' => 2,'isHomeSafe' => true,'isreps' => true]);
        DB::table('exercises')->insert(['id' => 144,'label' => 'Russian Twist Hard','exercisetype_id' => 5,'difficulty_id' => 3,'isHomeSafe' => true,'isreps' => true]);
        DB::table('exercises')->insert(['id' => 132,'label' => 'Scissor Kicks','exercisetype_id' => 5,'difficulty_id' => 2,'isHomeSafe' => true,'isreps' => true]);
        DB::table('exercises')->insert(['id' => 194,'label' => 'Shoulder Cross Stretch','exercisetype_id' => 6,'difficulty_id' => 1,'isHomeSafe' => true,'isreps' => false]);
        DB::table('exercises')->insert(['id' => 96,'label' => 'Side Lunges','exercisetype_id' => 2,'difficulty_id' => 2,'isHomeSafe' => true,'isreps' => true]);
        DB::table('exercises')->insert(['id' => 71,'label' => 'Side Plank Oblique Crunch','exercisetype_id' => 5,'difficulty_id' => 2,'isHomeSafe' => true,'isreps' => true]);
        DB::table('exercises')->insert(['id' => 72,'label' => 'Side Star Plank','exercisetype_id' => 5,'difficulty_id' => 2,'isHomeSafe' => true,'isreps' => false]);
        DB::table('exercises')->insert(['id' => 12,'label' => 'Side-to-Side Push-ups','exercisetype_id' => 1,'difficulty_id' => 2,'isHomeSafe' => true,'isreps' => true]);
        DB::table('exercises')->insert(['id' => 154,'label' => 'Single Leg Bridge','exercisetype_id' => 2,'difficulty_id' => 1,'isHomeSafe' => true,'isreps' => true]);
        DB::table('exercises')->insert(['id' => 100,'label' => 'Single Leg Deadlift','exercisetype_id' => 2,'difficulty_id' => 2,'isHomeSafe' => true,'isreps' => true]);
        DB::table('exercises')->insert(['id' => 167,'label' => 'Single Leg Pike Push-ups','exercisetype_id' => 1,'difficulty_id' => 3,'isHomeSafe' => true,'isreps' => true]);
        DB::table('exercises')->insert(['id' => 21,'label' => 'Single Leg Push-ups','exercisetype_id' => 1,'difficulty_id' => 3,'isHomeSafe' => true,'isreps' => true]);
        DB::table('exercises')->insert(['id' => 138,'label' => 'Single Leg V-ups','exercisetype_id' => 5,'difficulty_id' => 2,'isHomeSafe' => true,'isreps' => true]);
        DB::table('exercises')->insert(['id' => 126,'label' => 'Sit-ups','exercisetype_id' => 5,'difficulty_id' => 1,'isHomeSafe' => true,'isreps' => true]);
        DB::table('exercises')->insert(['id' => 149,'label' => 'Skier Abs','exercisetype_id' => 5,'difficulty_id' => 3,'isHomeSafe' => false,'isreps' => true]);
        DB::table('exercises')->insert(['id' => 158,'label' => 'Skier Jumps','exercisetype_id' => 4,'difficulty_id' => 2,'isHomeSafe' => false,'isreps' => true]);
        DB::table('exercises')->insert(['id' => 159,'label' => 'Speed Skaters','exercisetype_id' => 4,'difficulty_id' => 2,'isHomeSafe' => false,'isreps' => true]);
        DB::table('exercises')->insert(['id' => 38,'label' => 'Squat Side Kick','exercisetype_id' => 2,'difficulty_id' => 2,'isHomeSafe' => true,'isreps' => true]);
        DB::table('exercises')->insert(['id' => 121,'label' => 'Squat Stars','exercisetype_id' => 4,'difficulty_id' => 3,'isHomeSafe' => false,'isreps' => true]);
        DB::table('exercises')->insert(['id' => 31,'label' => 'Squat to High Knee','exercisetype_id' => 2,'difficulty_id' => 1,'isHomeSafe' => true,'isreps' => true]);
        DB::table('exercises')->insert(['id' => 39,'label' => 'Squat to High Knee Jumps','exercisetype_id' => 2,'difficulty_id' => 2,'isHomeSafe' => false,'isreps' => true]);
        DB::table('exercises')->insert(['id' => 27,'label' => 'Squats','exercisetype_id' => 2,'difficulty_id' => 1,'isHomeSafe' => true,'isreps' => true]);
        DB::table('exercises')->insert(['id' => 119,'label' => 'Squatting Quick Feet','exercisetype_id' => 4,'difficulty_id' => 2,'isHomeSafe' => false,'isreps' => false]);
        DB::table('exercises')->insert(['id' => 7,'label' => 'Stagger Push-ups','exercisetype_id' => 1,'difficulty_id' => 2,'isHomeSafe' => true,'isreps' => true]);
        DB::table('exercises')->insert(['id' => 196,'label' => 'Standing Quadriceps Stretch','exercisetype_id' => 6,'difficulty_id' => 1,'isHomeSafe' => true,'isreps' => false]);
        DB::table('exercises')->insert(['id' => 116,'label' => 'Star Jacks','exercisetype_id' => 4,'difficulty_id' => 2,'isHomeSafe' => false,'isreps' => true]);
        DB::table('exercises')->insert(['id' => 151,'label' => 'Straight Leg Bicycle Crunches','exercisetype_id' => 5,'difficulty_id' => 3,'isHomeSafe' => true,'isreps' => true]);
        DB::table('exercises')->insert(['id' => 128,'label' => 'Superman','exercisetype_id' => 5,'difficulty_id' => 1,'isHomeSafe' => true,'isreps' => true]);
        DB::table('exercises')->insert(['id' => 141,'label' => 'Superman Pull','exercisetype_id' => 5,'difficulty_id' => 2,'isHomeSafe' => true,'isreps' => true]);
        DB::table('exercises')->insert(['id' => 99,'label' => 'Touchdown Lunges','exercisetype_id' => 2,'difficulty_id' => 2,'isHomeSafe' => true,'isreps' => true]);
        DB::table('exercises')->insert(['id' => 163,'label' => 'Triceps Dip','exercisetype_id' => 1,'difficulty_id' => 1,'isHomeSafe' => true,'isreps' => true]);
        DB::table('exercises')->insert(['id' => 122,'label' => 'Tuck Jumps','exercisetype_id' => 4,'difficulty_id' => 3,'isHomeSafe' => false,'isreps' => true]);
        DB::table('exercises')->insert(['id' => 24,'label' => 'Typewriter Push-ups','exercisetype_id' => 1,'difficulty_id' => 3,'isHomeSafe' => true,'isreps' => true]);
        DB::table('exercises')->insert(['id' => 85,'label' => 'Ultimate Burpees','exercisetype_id' => 3,'difficulty_id' => 3,'isHomeSafe' => false,'isreps' => true]);
        DB::table('exercises')->insert(['id' => 14,'label' => 'Up Down Push-ups','exercisetype_id' => 1,'difficulty_id' => 2,'isHomeSafe' => true,'isreps' => true]);
        DB::table('exercises')->insert(['id' => 169,'label' => 'Up Downs','exercisetype_id' => 1,'difficulty_id' => 3,'isHomeSafe' => true,'isreps' => true]);
        DB::table('exercises')->insert(['id' => 146,'label' => 'V-ups','exercisetype_id' => 5,'difficulty_id' => 3,'isHomeSafe' => true,'isreps' => true]);
        DB::table('exercises')->insert(['id' => 197,'label' => 'Walking High Knees','exercisetype_id' => 4,'difficulty_id' => 1,'isHomeSafe' => true,'isreps' => true]);
        DB::table('exercises')->insert(['id' => 90,'label' => 'Walking Lunges','exercisetype_id' => 2,'difficulty_id' => 1,'isHomeSafe' => false,'isreps' => true]);
        DB::table('exercises')->insert(['id' => 175,'label' => 'Wall Bridge','exercisetype_id' => 2,'difficulty_id' => 1,'isHomeSafe' => true,'isreps' => true]);
        DB::table('exercises')->insert(['id' => 181,'label' => 'Wall Climbs','exercisetype_id' => 3,'difficulty_id' => 3,'isHomeSafe' => true,'isreps' => true]);
        DB::table('exercises')->insert(['id' => 184,'label' => 'Wall Handstand Kick Up','exercisetype_id' => 3,'difficulty_id' => 2,'isHomeSafe' => true,'isreps' => true]);
        DB::table('exercises')->insert(['id' => 192,'label' => 'Wall Pectoral Stretch','exercisetype_id' => 6,'difficulty_id' => 1,'isHomeSafe' => true,'isreps' => false]);
        DB::table('exercises')->insert(['id' => 172,'label' => 'Wall Push Offs','exercisetype_id' => 1,'difficulty_id' => 1,'isHomeSafe' => true,'isreps' => true]);
        DB::table('exercises')->insert(['id' => 173,'label' => 'Wall Sit','exercisetype_id' => 2,'difficulty_id' => 1,'isHomeSafe' => true,'isreps' => false]);
        DB::table('exercises')->insert(['id' => 145,'label' => 'Wide Climber Jumps','exercisetype_id' => 5,'difficulty_id' => 3,'isHomeSafe' => false,'isreps' => true]);
        DB::table('exercises')->insert(['id' => 108,'label' => 'Wide High Knees','exercisetype_id' => 4,'difficulty_id' => 1,'isHomeSafe' => false,'isreps' => true]);
        DB::table('exercises')->insert(['id' => 3,'label' => 'Wide Knee Push-ups','exercisetype_id' => 1,'difficulty_id' => 1,'isHomeSafe' => true,'isreps' => true]);
        DB::table('exercises')->insert(['id' => 147,'label' => 'Wide Legged V-ups','exercisetype_id' => 5,'difficulty_id' => 3,'isHomeSafe' => true,'isreps' => true]);
        DB::table('exercises')->insert(['id' => 6,'label' => 'Wide Push-ups','exercisetype_id' => 1,'difficulty_id' => 1,'isHomeSafe' => true,'isreps' => true]);
        DB::table('exercises')->insert(['id' => 148,'label' => 'Windshield Wipers','exercisetype_id' => 5,'difficulty_id' => 3,'isHomeSafe' => true,'isreps' => true]);
        DB::table('exercises')->insert(['id' => 1000,'label' => 'Pause','exercisetype_id' => 3,'difficulty_id' => 1,'isHomeSafe' => true,'isreps' => false]);
    }
}
